// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameOrg = "org"

// Org mapped from table <org>
type Org struct {
	ID         string    `gorm:"column:id;type:bigint;primaryKey;comment:ID" json:"id"`                                     // ID
	CreateTime time.Time `gorm:"column:create_time;type:timestamp with time zone;not null;comment:创建时间" json:"create_time"` // 创建时间
	UpdateTime time.Time `gorm:"column:update_time;type:timestamp with time zone;not null;comment:更新时间" json:"update_time"` // 更新时间
	Status     *bool     `gorm:"column:status;type:boolean;not null;default:true;comment:状态" json:"status"`                 // 状态
	Type       *int16    `gorm:"column:type;type:smallint;not null;default:1;comment:组织类型" json:"type"`                     // 组织类型
	Name       string    `gorm:"column:name;type:text;not null;comment:组织名称" json:"name"`                                   // 组织名称
}

// TableName Org's table name
func (*Org) TableName() string {
	return TableNameOrg
}
