// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNamePermission = "permission"

// Permission mapped from table <permission>
type Permission struct {
	ID          string `gorm:"column:id;type:bigint;primaryKey;comment:ID" json:"id"`               // ID
	Key         string `gorm:"column:key;type:text;not null;comment:能力标识" json:"key"`               // 能力标识
	Description string `gorm:"column:description;type:text;not null;comment:描述" json:"description"` // 描述
}

// TableName Permission's table name
func (*Permission) TableName() string {
	return TableNamePermission
}
