// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"litho-api/common"
	"time"
)

const TableNameResource = "resource"

// Resource mapped from table <resource>
type Resource struct {
	ID         string         `gorm:"column:id;type:text;primaryKey;comment:ID标识" json:"id"`                                                   // ID标识
	Name       string         `gorm:"column:name;type:text;not null;comment:资源名称" json:"name"`                                                 // 资源名称
	Actions    common.Actions `gorm:"column:actions;type:jsonb;not null;default:[];comment:操作集合" json:"actions"`                               // 操作集合
	CreateTime *time.Time     `gorm:"column:create_time;type:timestamp with time zone;not null;default:now();comment:创建时间" json:"create_time"` // 创建时间
	UpdateTime *time.Time     `gorm:"column:update_time;type:timestamp with time zone;not null;default:now();comment:更新时间" json:"update_time"` // 更新时间
}

// TableName Resource's table name
func (*Resource) TableName() string {
	return TableNameResource
}
