package model

import (
	"testing"
)

func TestResource(t *testing.T) {
	if err := db.AutoMigrate(&Resource{}); err != nil {
		t.Error(err)
	}
	data := []Resource{
		{
			ID:       1,
			Parent:   0,
			Fragment: "dashboard",
			Name:     "仪表盘",
			Nav:      True(),
			Router:   False(),
			Icon:     "dashboard",
		},
		{
			ID:       2,
			Parent:   1,
			Fragment: "analysis",
			Name:     "分析页",
			Nav:      True(),
			Router:   True(),
			Icon:     "",
		},
		{
			ID:       3,
			Parent:   1,
			Fragment: "monitor",
			Name:     "监控页",
			Nav:      True(),
			Router:   True(),
			Icon:     "",
		},
		{
			ID:       4,
			Parent:   1,
			Fragment: "workbench",
			Name:     "工作台",
			Nav:      True(),
			Router:   True(),
			Icon:     "",
		},
		{
			ID:       20,
			Parent:   0,
			Fragment: "form",
			Name:     "表单页",
			Nav:      True(),
			Router:   False(),
			Icon:     "form",
		},
		{
			ID:       21,
			Parent:   20,
			Fragment: "basic",
			Name:     "基础表单",
			Nav:      True(),
			Router:   True(),
			Icon:     "",
		},
		{
			ID:       22,
			Parent:   20,
			Fragment: "step",
			Name:     "分步表单",
			Nav:      True(),
			Router:   True(),
			Icon:     "",
		},
		{
			ID:       23,
			Parent:   20,
			Fragment: "advanced",
			Name:     "高级表单",
			Nav:      True(),
			Router:   True(),
			Icon:     "",
		},
		// 列表页
		{
			ID:       40,
			Parent:   0,
			Fragment: "list",
			Name:     "列表页",
			Nav:      True(),
			Router:   False(),
			Icon:     "table",
		},
		{
			ID:       41,
			Parent:   40,
			Fragment: "table",
			Name:     "查询表格",
			Nav:      True(),
			Router:   True(),
			Icon:     "",
		},
		{
			ID:       42,
			Parent:   40,
			Fragment: "basic",
			Name:     "标准列表",
			Nav:      True(),
			Router:   True(),
			Icon:     "",
		},
		{
			ID:       43,
			Parent:   40,
			Fragment: "card",
			Name:     "卡片列表",
			Nav:      True(),
			Router:   True(),
			Icon:     "",
		},
		// 详情页
		{
			ID:       60,
			Parent:   0,
			Fragment: "profile",
			Name:     "详情页",
			Nav:      True(),
			Router:   False(),
			Icon:     "profile",
		},
		{
			ID:       61,
			Parent:   60,
			Fragment: "basic",
			Name:     "基础详情页",
			Nav:      True(),
			Router:   True(),
			Icon:     "",
		},
		{
			ID:       62,
			Parent:   60,
			Fragment: "advanced",
			Name:     "高级详情页",
			Nav:      True(),
			Router:   True(),
			Icon:     "",
		},
		// 结果页
		{
			ID:       80,
			Parent:   0,
			Fragment: "result",
			Name:     "结果页",
			Nav:      True(),
			Router:   False(),
			Icon:     "check-circle",
		},
		{
			ID:       81,
			Parent:   80,
			Fragment: "success",
			Name:     "成功页",
			Nav:      True(),
			Router:   True(),
			Icon:     "",
		},
		{
			ID:       82,
			Parent:   80,
			Fragment: "fail",
			Name:     "失败页",
			Nav:      True(),
			Router:   True(),
			Icon:     "",
		},
		// 异常页
		{
			ID:       100,
			Parent:   0,
			Fragment: "exception",
			Name:     "异常页",
			Nav:      True(),
			Router:   False(),
			Icon:     "warning",
		},
		{
			ID:       101,
			Parent:   100,
			Fragment: "403",
			Name:     "403",
			Nav:      True(),
			Router:   True(),
			Icon:     "",
		},
		{
			ID:       102,
			Parent:   100,
			Fragment: "404",
			Name:     "404",
			Nav:      True(),
			Router:   True(),
			Icon:     "",
		},
		{
			ID:       103,
			Parent:   100,
			Fragment: "500",
			Name:     "500",
			Nav:      True(),
			Router:   True(),
			Icon:     "",
		},
	}

	db.Create(&data)
}
