// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"litho-api/common"
	"time"
)

const TableNameRole = "role"

// Role mapped from table <role>
type Role struct {
	ID          string              `gorm:"column:id;type:bigint;primaryKey;comment:ID" json:"id"`                                     // ID
	CreateTime  time.Time           `gorm:"column:create_time;type:timestamp with time zone;not null;comment:创建时间" json:"create_time"` // 创建时间
	UpdateTime  time.Time           `gorm:"column:update_time;type:timestamp with time zone;not null;comment:更新时间" json:"update_time"` // 更新时间
	Sort        int16               `gorm:"column:sort;type:smallint;not null;comment:排序" json:"sort"`                                 // 排序
	Status      *bool               `gorm:"column:status;type:boolean;not null;default:true;comment:状态" json:"status"`                 // 状态
	Name        string              `gorm:"column:name;type:text;not null;comment:权限名称" json:"name"`                                   // 权限名称
	Description string              `gorm:"column:description;type:text;not null;comment:权限描述" json:"description"`                     // 权限描述
	Strategy    common.RoleStrategy `gorm:"column:strategy;type:jsonb;not null;default:{};comment:策略" json:"strategy"`                 // 策略
}

// TableName Role's table name
func (*Role) TableName() string {
	return TableNameRole
}
