// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"litho-api/common"
	"time"
)

const TableNameRoute = "route"

// Route mapped from table <route>
type Route struct {
	ID         string               `gorm:"column:id;type:bigint;primaryKey;comment:ID" json:"id"`                                          // ID
	CreateTime time.Time            `gorm:"column:create_time;type:timestamp with time zone;not null;comment:创建时间" json:"create_time"`      // 创建时间
	UpdateTime time.Time            `gorm:"column:update_time;type:timestamp with time zone;not null;comment:更新时间" json:"update_time"`      // 更新时间
	Sort       int16                `gorm:"column:sort;type:smallint;not null;comment:排序" json:"sort"`                                      // 排序
	Status     *bool                `gorm:"column:status;type:boolean;not null;default:true;comment:状态" json:"status"`                      // 状态
	Nav        string               `gorm:"column:nav;type:text;not null;comment:导航" json:"nav"`                                            // 导航
	Pid        string               `gorm:"column:pid;type:bigint;not null;comment:分组ID" json:"pid"`                                        // 分组ID
	Name       string               `gorm:"column:name;type:text;not null;comment:路由名称" json:"name"`                                        // 路由名称
	Type       *int16               `gorm:"column:type;type:smallint;not null;default:1;comment:路由类型（1，分组；2，页面；3，外链；4，iframe）" json:"type"` // 路由类型（1，分组；2，页面；3，外链；4，iframe）
	Icon       string               `gorm:"column:icon;type:text;not null;comment:字体图标" json:"icon"`                                        // 字体图标
	Link       string               `gorm:"column:link;type:text;not null;comment:链接" json:"link"`                                          // 链接
	Strategy   common.RouteStrategy `gorm:"column:strategy;type:jsonb;not null;default:{};comment:策略" json:"strategy"`                      // 策略
}

// TableName Route's table name
func (*Route) TableName() string {
	return TableNameRoute
}
