// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUser = "user"

// User mapped from table <user>
type User struct {
	ID         string     `gorm:"column:id;type:bigint;primaryKey;comment:ID" json:"id"`                                                   // ID
	CreateTime time.Time  `gorm:"column:create_time;type:timestamp with time zone;not null;comment:创建时间" json:"create_time"`               // 创建时间
	UpdateTime time.Time  `gorm:"column:update_time;type:timestamp with time zone;not null;comment:更新时间" json:"update_time"`               // 更新时间
	Status     *bool      `gorm:"column:status;type:boolean;not null;default:true;comment:状态" json:"status"`                               // 状态
	OrgID      string     `gorm:"column:org_id;type:bigint;not null;comment:所属组织" json:"org_id"`                                           // 所属组织
	RoleID     string     `gorm:"column:role_id;type:bigint;not null;comment:所属权限" json:"role_id"`                                         // 所属权限
	Email      string     `gorm:"column:email;type:text;not null;comment:电子邮件" json:"email"`                                               // 电子邮件
	Phone      string     `gorm:"column:phone;type:text;not null;comment:手机号" json:"phone"`                                                // 手机号
	Name       string     `gorm:"column:name;type:text;not null;comment:姓名" json:"name"`                                                   // 姓名
	Password   string     `gorm:"column:password;type:text;not null;comment:密码" json:"password"`                                           // 密码
	Avatar     string     `gorm:"column:avatar;type:text;not null;comment:头像" json:"avatar"`                                               // 头像
	Sessions   int32      `gorm:"column:sessions;type:integer;not null;comment:会话次数" json:"sessions"`                                      // 会话次数
	LoginTime  *time.Time `gorm:"column:login_time;type:timestamp with time zone;not null;default:now();comment:最近登录时间" json:"login_time"` // 最近登录时间
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
