// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/goforj/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package bootstrap

import (
	"litho-api/api"
	"litho-api/api/index"
	"litho-api/api/orgs"
	"litho-api/api/permissions"
	"litho-api/api/resources"
	"litho-api/api/roles"
	"litho-api/api/routes"
	"litho-api/api/sessions"
	"litho-api/api/users"
	"litho-api/common"
)

// Injectors from wire.go:

func NewAPI(values *common.Values) (*api.API, error) {
	db, err := UseGorm(values)
	if err != nil {
		return nil, err
	}
	client, err := UseRedis(values)
	if err != nil {
		return nil, err
	}
	conn, err := UseNats(values)
	if err != nil {
		return nil, err
	}
	jetStream, err := UseJetStream(conn)
	if err != nil {
		return nil, err
	}
	cipher, err := UseCipher(values)
	if err != nil {
		return nil, err
	}
	captcha := UseCaptcha(client)
	locker := UseLocker(client)
	inject := &common.Inject{
		V:       values,
		Db:      db,
		RDb:     client,
		Nc:      conn,
		Js:      jetStream,
		Cipher:  cipher,
		Captcha: captcha,
		Locker:  locker,
	}
	hertz, err := UseHertz(values)
	if err != nil {
		return nil, err
	}
	csrf := UseCsrf(values)
	service := &permissions.Service{
		Inject: inject,
	}
	controller := &permissions.Controller{
		PermissionsX: service,
	}
	passport := UsePassport(values)
	sessionsService := &sessions.Service{
		Inject: inject,
	}
	indexService := &index.Service{
		Inject:    inject,
		Passport:  passport,
		SessionsX: sessionsService,
	}
	indexController := &index.Controller{
		V:      values,
		IndexX: indexService,
	}
	orgsService := &orgs.Service{
		Inject: inject,
	}
	orgsController := &orgs.Controller{
		OrgsX: orgsService,
	}
	resourcesService := &resources.Service{
		Inject: inject,
	}
	resourcesController := &resources.Controller{
		ResourcesX: resourcesService,
	}
	rolesService := &roles.Service{
		Inject: inject,
	}
	rolesController := &roles.Controller{
		RolesX: rolesService,
	}
	routesService := &routes.Service{
		Inject: inject,
	}
	routesController := &routes.Controller{
		RoutesX: routesService,
	}
	sessionsController := &sessions.Controller{
		SessionsX: sessionsService,
	}
	usersService := &users.Service{
		Inject:    inject,
		SessionsX: sessionsService,
		OrgsX:     orgsService,
	}
	usersController := &users.Controller{
		UsersX: usersService,
	}
	apiAPI := &api.API{
		Inject:      inject,
		Hertz:       hertz,
		Csrf:        csrf,
		Permissions: controller,
		Index:       indexController,
		IndexX:      indexService,
		Orgs:        orgsController,
		Resources:   resourcesController,
		Roles:       rolesController,
		RolesX:      rolesService,
		Routes:      routesController,
		Sessions:    sessionsController,
		Users:       usersController,
		UsersX:      usersService,
	}
	return apiAPI, nil
}
