name: 'weplanx'
key: '<A key of length 32>'
database:
  dsn: 'host=localhost user=weplanx password=pass dbname=weplanx'
  max_idle_conns: 10
  max_open_conns: 100
  conn_max_lifetime: 3600
redis:
  address: localhost:6379
  password:
  db: 0
cookie:
  secure: true
  http_only: true
  same_site: strict
cors: [ 'https://api.developer.com' ]
auth:
  system:
    aud: [ 'admin' ]
    exp: 720
