name: 'weplanx'
key: '<A key of length 32>'
database:
  uri: mongodb://$[username]:$[password]@$[host]:$[port]/$[database]?authSource=admin
  name: weplanx
redis:
  address: localhost:6379
  password:
  db: 0
cookie:
  secure: true
  http_only: true
  same_site: strict
cors: [ 'https://sys.anysite.com' ]
auth:
  system:
    aud: [ 'admin' ]
    exp: 720
