listen: ':8000'
app:
  name: lab
  debug: true
  lock:
    limit: 5
    recovery_time: 900
auth:
  key:
  issuer: lab-api
  audience: [ console ]
  not_before: 0
  expires: 3600
database:
  dsn: user:pass@tcp(127.0.0.1:3306)/dbname?charset=utf8mb4&parseTime=True&loc=Local
  max_idle_conns: 10
  max_open_conns: 100
  conn_max_lifetime: 3600
  table_prefix:
redis:
  address: localhost:6379
  password:
  db: 0
cors:
  origin:
    - *
  method:
    - POST
    - OPTIONS
  allow_header:
    - CONTENT-TYPE
    - X-REQUESTED-WITH
  exposed_header:
  max_age: 86400
  credentials: false
storage:
  type: cos
  option:
    secret_id:
    secret_key:
    region:
    bucket:
