address: ":9000"
trusted_proxies: []
name: <app name>
key: <a key of length 32>
database:
  uri: mongodb://<username>:<password>@<host>:<port>/<database>?authSource=<authSource>
  dbName: <database>
redis:
  uri: redis://<user>:<password>@<host>:<port>/<db_number>
cors:
  allowOrigins:
    - https://app.developer.com
  allowMethods:
    - POST
  allowHeaders:
    - Content-Type
    - Accept
  allowCredentials: true
  maxAge: 7200
passport:
  aud: [ 'console' ]
  exp: 720
