name: 'weplanx'
key: '<a key of length 32>'
database:
  uri: mongodb://$[username]:$[password]@$[host]:$[port]/$[database]?authSource=admin
  name: weplanx
redis:
  address: $[host]:6379
  password: $[password]
  db: 0
cookie:
  secure: true
  http_only: true
cors: [ 'https://sys.awesome.com' ]
auth:
  system:
    aud: [ 'system' ]
    exp: 720
