version: '3.7'
services:
  update:
    image: kainonly/composer-alpine
    command: 'composer update --prefer-dist -o --no-dev --ignore-platform-reqs'
    volumes:
      - ../composer:/tmp
      - ./:/app
