version: '3.7'
services:
  swoole:
    image: kainonly/swoole-alpine
    restart: always
    command: 'php bin/hyperf.php start'
    volumes:
      - ./:/app
    ports:
      - 9501:9501
  translation:
    image: kainonly/swoole-alpine
    command: 'php bin/hyperf.php vendor:publish hyperf/translation'
    volumes:
      - ./:/app
  validation:
    image: kainonly/swoole-alpine
    command: 'php bin/hyperf.php vendor:publish hyperf/validation'
    volumes:
      - ./:/app
  update:
    image: kainonly/composer-alpine
    command: 'composer update --prefer-dist -o --no-dev --ignore-platform-reqs'
    volumes:
      - ../../composer:/tmp
      - ./:/app
