// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gin-gonic/gin"
	"github.com/weplanx/server/api"
	"github.com/weplanx/server/api/app"
	"github.com/weplanx/server/bootstrap"
	"github.com/weplanx/server/common"
)

// Injectors from wire.go:

func OkLetsGo(value *common.Values) (*gin.Engine, error) {
	apiAPI := &api.API{
		Values: value,
	}
	client, err := bootstrap.UseMongoDB(value)
	if err != nil {
		return nil, err
	}
	database := bootstrap.UseDatabase(client, value)
	redisClient, err := bootstrap.UseRedis(value)
	if err != nil {
		return nil, err
	}
	inject := &common.Inject{
		Values: value,
		Mongo:  client,
		Db:     database,
		Redis:  redisClient,
	}
	service := &app.Service{
		Inject: inject,
	}
	controller := &app.Controller{
		AppService: service,
	}
	engine := api.Routes(apiAPI, controller)
	return engine, nil
}
