package devtools

const modelTpl = `
// Code generated by bit. DO NOT EDIT.

package model

import (
	"github.com/google/uuid"
	"gorm.io/gorm"
	"time"
)

{{range .}}
type {{title .Key}} struct {` +
	"ID     	int64	   `json:\"id\"`\n" +
	"Status     *bool      `gorm:\"default:true\" json:\"status\"`\n" +
	"CreateTime time.Time  `gorm:\"autoCreateTime;default:current_timestamp\" json:\"create_time\"`\n" +
	"UpdateTime time.Time  `gorm:\"autoUpdateTime;default:current_timestamp\" json:\"update_time\"`" + `
	{{columns .Columns}}
}
{{end}}

func AutoMigrate(tx *gorm.DB, models ...string) (err error) {
	mapper := map[string]interface{}{
		{{range .}}"{{ .Key}}": &{{title .Key}}{},{{end}}
	}

	for _, model := range models {
		if mapper[model] != nil {
			if err = tx.AutoMigrate(mapper[model]); err != nil {
				return
			}
		}
	}

	return
}
`
