address: ":9000"
# 不设置将无法获取到客户端 ip，也可以使用七层反向代理做上游（例如：全站加速、应用负载均衡等）
trusted_proxies:
  - 10.42.0.0/16
namespace: <应用名称>
key: <32位密文>
database:
  uri: mongodb://<username>:<password>@<host>:<port>/<database>?authSource=<authSource>
  dbName: <database>
redis:
  uri: redis://<user>:<password>@<host>:<port>/<db_number>
nats:
  hosts: [ ]
  nkey:
cors:
  allowOrigins:
    - https://app.****.com
  allowMethods:
    - POST
  allowHeaders:
    - Content-Type
    - Accept
  allowCredentials: true
  maxAge: 7200
passport:
  aud: [ 'console' ]
  exp: 720
qcloud:
  secret_id: <secret_id>
  secret_key: <secret_key>
  cos:
    bucket: examplebucket-****
    region: ap-guangzhou
    expired: 300
engines:
  pages:
    event: true
  users:
    projection:
      password: 0