apiVersion: v1
kind: ConfigMap
metadata:
  name: api.cfg
data:
  config.yml: |
    address: ":9000"
    # 不设置将无法获取到客户端 ip，也可以使用七层反向代理做上游（例如：全站加速、应用负载均衡等）
    trusted_proxies:
      - 10.42.0.0/16
    name: <应用名称>
    key: <32位密文>
    database:
      uri: mongodb://<username>:<password>@<host>:<port>/<database>?authSource=<authSource>
      dbName: <database>
    redis:
      uri: redis://<user>:<password>@<host>:<port>/<db_number>
    pulsar:
      url: http://pulsar-****:8080
      token: <密钥>
      topics:
        event: persistent://<集群租户ID>/<命名空间>/
    cors:
      allowOrigins:
        - https://app.****.com
      allowMethods:
        - POST
      allowHeaders:
        - Content-Type
        - Accept
      allowCredentials: true
      maxAge: 7200
    passport:
      aud: [ 'console' ]
      exp: 720
    qcloud:
      secret_id: <secret_id>
      secret_key: <secret_key>
      cos:
        bucket: examplebucket-****
        region: ap-guangzhou
        expired: 300
    engines:
      pages:
        event: persistent://<集群租户ID>/<命名空间>/
      users:
        projection:
          password: 0