apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api
  name: api-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - image: ccr.ccs.tencentyun.com/weplanx/api:latest
          imagePullPolicy: Always
          name: api
          ports:
            - containerPort: 9000
          volumeMounts:
            - name: config
              mountPath: "/app/config"
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: api.cfg
            items:
              - key: "config.yml"
                path: "config.yml"
---
apiVersion: v1
kind: Service
metadata:
  name: api-svc
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 9000
  selector:
    app: api
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api
  annotations:
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.tls.certresolver: "****"
    traefik.ingress.kubernetes.io/router.tls.domains.0.main: "****.com"
    traefik.ingress.kubernetes.io/router.tls.domains.0.sans: "*.****.com"
spec:
  rules:
    - host: api.****.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: api-svc
                port:
                  number: 80