apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  labels:
    app: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - image: ccr.ccs.tencentyun.com/weplanx/server:v0.1.0
          imagePullPolicy: Always
          name: server
          env:
            - name: MODE
              value: release
            - name: NAMESPACE
              value: weplanx
            - name: KEY
              value: you key...
            - name: DATABASE_URL
              value: mongodb+srv://...
            - name: DATABASE_NAME
              value: weplanx
            - name: DATABASE_REDIS
              value: redis://...
            - name: INFLUX_URL
              value: ...
            - name: INFLUX_ORG
              value: ...
            - name: INFLUX_TOKEN
              value: ...
            - name: INFLUX_BUCKET
              value: ...
            - name: NATS_HOSTS
              value: tls://
            - name: NATS_NKEY
              value: you nkey...
            - name: OTLP_ENDPOINT
              value: ...
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: server
spec:
  ports:
    - port: 3000
      protocol: TCP
  selector:
    app: server
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: server-stripprefix
spec:
  stripPrefix:
    prefixes:
      - /api
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: server
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.middlewares: default-server-stripprefix@kubernetescrd
spec:
  rules:
    - host: console.example.com
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: server
                port:
                  number: 3000
