// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ResourcesColumns holds the columns for the "resources" table.
	ResourcesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "path", Type: field.TypeString, Unique: true},
		{Name: "parent", Type: field.TypeString, Default: "root"},
		{Name: "router", Type: field.TypeBool},
		{Name: "nav", Type: field.TypeBool},
		{Name: "icon", Type: field.TypeString, Nullable: true},
		{Name: "sort", Type: field.TypeUint},
	}
	// ResourcesTable holds the schema information for the "resources" table.
	ResourcesTable = &schema.Table{
		Name:       "resources",
		Columns:    ResourcesColumns,
		PrimaryKey: []*schema.Column{ResourcesColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ResourcesTable,
	}
)

func init() {
}
