// Code generated by entc, DO NOT EDIT.

package ent

import (
	"lab-api/ent/resource"
	"lab-api/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	resourceFields := schema.Resource{}.Fields()
	_ = resourceFields
	// resourceDescParent is the schema descriptor for parent field.
	resourceDescParent := resourceFields[2].Descriptor()
	// resource.DefaultParent holds the default value on creation for the parent field.
	resource.DefaultParent = resourceDescParent.Default.(string)
}
