name: release

on:
  release:
    types: [ published ]

env:
  REGISTRY: ghcr.io
  QCLOUD_REGISTRY: ccr.ccs.tencentyun.com
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup Golang
        uses: actions/setup-go@v2
        with:
          go-version: ^1.17

      - name: Build Application
        run: go build -tags=jsoniter -o dist/main main.go wire_gen.go
        env:
          CGO_ENABLED: 0
          GO111MODULE: on
          GOARCH: amd64
          GOOS: linux

      - name: Log in to GitHub Container Hub
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in to TCR
        uses: docker/login-action@v1
        with:
          registry: ${{ env.QCLOUD_REGISTRY }}
          username: ${{ secrets.QCLOUD_USERNAME }}
          password: ${{ secrets.QCLOUD_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        env:
          GIN_MODE: release
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Push Image to multiple registries
        uses: akhilerm/tag-push-action@v2.0.0
        with:
          src: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{steps.meta.outputs.version}}
          dst: |
            ${{ env.QCLOUD_REGISTRY }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.QCLOUD_REGISTRY }}/${{ env.IMAGE_NAME }}:${{steps.meta.outputs.version}}

      - name: Setup Kubectl & Patch Deployment
        uses: steebchen/kubectl@v2.0.0
        with:
          config: ${{ secrets.KUBE_CONFIG }}
          version: v1.23.1
          command: patch deployment api-deploy --patch "$(sed "s/\${tag}/${{steps.meta.outputs.version}}/" < ./config/patch.yml)"