// Code generated by entc, DO NOT EDIT.

package resource

const (
	// Label holds the string label denoting the resource type in the database.
	Label = "resource"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldPath holds the string denoting the path field in the database.
	FieldPath = "path"
	// FieldParent holds the string denoting the parent field in the database.
	FieldParent = "parent"
	// FieldRouter holds the string denoting the router field in the database.
	FieldRouter = "router"
	// FieldNav holds the string denoting the nav field in the database.
	FieldNav = "nav"
	// FieldIcon holds the string denoting the icon field in the database.
	FieldIcon = "icon"
	// FieldSort holds the string denoting the sort field in the database.
	FieldSort = "sort"
	// Table holds the table name of the resource in the database.
	Table = "resources"
)

// Columns holds all SQL columns for resource fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldPath,
	FieldParent,
	FieldRouter,
	FieldNav,
	FieldIcon,
	FieldSort,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultParent holds the default value on creation for the "parent" field.
	DefaultParent string
)
